// periodicTableData.ts
export const periodicTableData = [
  // 4th row
  [
    { className: "AlMetals", symbol: "K", name: "Potassium", number: 19 },
    { className: "AlEarthMetals", symbol: "Ca", name: "Calcium", number: 20 },
    { className: "tMetals", symbol: "Sc", name: "Scandium", number: 21 },
    { className: "tMetals", symbol: "Ti", name: "Titanium", number: 22 },
    { className: "tMetals", symbol: "V", name: "Vanadium", number: 23 },
    { className: "tMetals", symbol: "Cr", name: "Chromium", number: 24 },
    { className: "tMetals", symbol: "Mn", name: "Manganese", number: 25 },
    { className: "tMetals", symbol: "Fe", name: "Iron", number: 26 },
    { className: "tMetals", symbol: "Co", name: "Cobalt", number: 27 },
    { className: "tMetals", symbol: "Ni", name: "Nickel", number: 28 },
    { className: "tMetals", symbol: "Cu", name: "Copper", number: 29 },
    { className: "tMetals", symbol: "Zn", name: "Zinc", number: 30 },
    { className: "metalloids", symbol: "Ga", name: "Gallium", number: 31 },
    { className: "metalloids", symbol: "Ge", name: "Germanium", number: 32 },
    { className: "nonMetal", symbol: "As", name: "Arsenic", number: 33 },
    { className: "nonMetal", symbol: "Se", name: "Selenium", number: 34 },
    { className: "halogens", symbol: "Br", name: "Bromine", number: 35 },
    { className: "nobleGases", symbol: "Kr", name: "Krypton", number: 36 },
  ],
  // 5th row
  [
    { className: "AlMetals", symbol: "Rb", name: "Rubidium", number: 37 },
    { className: "AlEarthMetals", symbol: "Sr", name: "Strontium", number: 38 },
    { className: "tMetals", symbol: "Y", name: "Yttrium", number: 39 },
    { className: "tMetals", symbol: "Zr", name: "Zirconium", number: 40 },
    { className: "tMetals", symbol: "Nb", name: "Niobium", number: 41 },
    { className: "tMetals", symbol: "Mo", name: "Molybdenum", number: 42 },
    { className: "tMetals", symbol: "Tc", name: "Technetium", number: 43 },
    { className: "tMetals", symbol: "Ru", name: "Ruthenium", number: 44 },
    { className: "tMetals", symbol: "Rh", name: "Rhodium", number: 45 },
    { className: "tMetals", symbol: "Pd", name: "Palladium", number: 46 },
    { className: "tMetals", symbol: "Ag", name: "Silver", number: 47 },
    { className: "tMetals", symbol: "Cd", name: "Cadmium", number: 48 },
    { className: "oMetals", symbol: "In", name: "Indium", number: 49 },
    { className: "oMetals", symbol: "Sn", name: "Tin", number: 50 },
    { className: "nonMetal", symbol: "Sb", name: "Antimony", number: 51 },
    { className: "nonMetal", symbol: "Te", name: "Tellurium", number: 52 },
    { className: "halogens", symbol: "I", name: "Iodine", number: 53 },
    { className: "nobleGases", symbol: "Xe", name: "Xenon", number: 54 },
  ],
  // 6th row
  [
    { className: "AlMetals", symbol: "Cs", name: "Cesium", number: 55 },
    { className: "AlEarthMetals", symbol: "Ba", name: "Barium", number: 56 },
    { className: "unknown", symbol: "La", name: "Lanthanum", number: 57 },
    { className: "tMetals", symbol: "Hf", name: "Hafnium", number: 72 },
    { className: "tMetals", symbol: "Ta", name: "Tantalum", number: 73 },
    { className: "tMetals", symbol: "W", name: "Tungsten", number: 74 },
    { className: "tMetals", symbol: "Re", name: "Rhenium", number: 75 },
    { className: "tMetals", symbol: "Os", name: "Osmium", number: 76 },
    { className: "tMetals", symbol: "Ir", name: "Iridium", number: 77 },
    { className: "tMetals", symbol: "Pt", name: "Platinum", number: 78 },
    { className: "tMetals", symbol: "Au", name: "Gold", number: 79 },
    { className: "tMetals", symbol: "Hg", name: "Mercury", number: 80 },
    { className: "oMetals", symbol: "Tl", name: "Thallium", number: 81 },
    { className: "oMetals", symbol: "Pb", name: "Lead", number: 82 },
    { className: "oMetals", symbol: "Bi", name: "Bismuth", number: 83 },
    { className: "nonMetal", symbol: "Po", name: "Polonium", number: 84 },
    { className: "halogens", symbol: "At", name: "Astatine", number: 85 },
    { className: "nobleGases", symbol: "Rn", name: "Radon", number: 86 },
  ],
  // 7th row
  [
    { className: "AlMetals", symbol: "Fr", name: "Francium", number: 87 },
    { className: "AlEarthMetals", symbol: "Ra", name: "Radium", number: 88 },
    { className: "unknown", symbol: "Ac", name: "Actinium", number: 89 },
    { className: "tMetals", symbol: "Rf", name: "Rutherfordium", number: 104 },
    { className: "tMetals", symbol: "Db", name: "Dubnium", number: 105 },
    { className: "tMetals", symbol: "Sg", name: "Seaborgium", number: 106 },
    { className: "tMetals", symbol: "Bh", name: "Bohrium", number: 107 },
    { className: "tMetals", symbol: "Hs", name: "Hassium", number: 108 },
    { className: "unknown", symbol: "Mt", name: "Meitnerium", number: 109 },
    { className: "unknown", symbol: "Ds", name: "Darmstadtium", number: 110 },
    { className: "unknown", symbol: "Rg", name: "Roentgenium", number: 111 },
    { className: "unknown", symbol: "Cn", name: "Copernicium", number: 112 },
    { className: "unknown", symbol: "Nh", name: "Nihonium", number: 113 },
    { className: "unknown", symbol: "Fl", name: "Flerovium", number: 114 },
    { className: "unknown", symbol: "Mc", name: "Moscovium", number: 115 },
    { className: "unknown", symbol: "Lv", name: "Livermorium", number: 116 },
    { className: "unknown", symbol: "Ts", name: "Tennessine", number: 117 },
    { className: "unknown", symbol: "Og", name: "Oganesson", number: 118 },
  ],
];
